---

dock_items_to_remove:
  - App Store
  - Contacts
  - FaceTime
  - iTunes
  - Launchpad
  - Maps
  - Photos
  - Reminders
  - Safari
  - Siri
  - News

dock_items_to_persist:
  Messages:
    path: /Applcations/Messages.app
    after: Finder
  Slack:
    path: /Applications/Slack.app
    after: Messages
  Google Chrome:
    path: "/Applications/Google Chrome.app"
    after: Mail
  iTerm:
    path: /Applications/iTerm.app
    after: Google Chrome
  Spotify:
    path: /Applications/Spotify.app
    after: iTerm
  Notes:
    path: /Applications/Notes.app
    after: Spotify
  System Preferences:
    path: "/Applications/System Preferences.app"
    after: Notes
  Obsidian:
    path: /Applications/Obsidian.app
    after: System Preferences

dock_settings:
  autohide:
    desc: turn on autohide
    type: bool
    value: true
  autohide-delay:
    type: float
    value: 0
    desc: remove autohide delay
  launchanim:
    desc: turn launch animation off
    type: bool
    value: false
  tilesize:
    desc: set tile size
    type: int
    value: 40
  mineffect:
    desc: minimization effect
    type: string
    value: scale
  mru-spaces:
    desc: prevent rearranging of 'spaces' based on use
    type: bool
    value: false
