---

- name: Create ~/.zsh dir
  file:
    path: ~/.zsh/completion
    state: directory
    recurse: yes

- name: Setup git-completion
  copy:
    src: "{{ item.value.src }}"
    dest: "{{ item.key }}"
    force: no
  with_dict:
    ~/.zsh/completion/git-completion.bash:
      src: git-completion.bash
    ~/.zsh/completion/_git:
      src: git-completion.zsh

- name: Copy Operator Mono fonts
  copy:
    src: "{{ item }}"
    dest: ~/Library/Fonts
    force: no
  with_fileglob: fonts/*

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    depth: 1

- name: Set permissions for oh-my-zsh
  file:
    path: ~/.oh-my-zsh
    mode: go-w
    recurse: yes
    state: directory

- name: Ensure tmux directory exists
  file:
    path: ~/.config/tmux
    state: directory

- name: Clone oh my tmux
  git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: ~/.config/tmux

- name: Symlink tmux.conf
  file:
    src: ~/.config/tmux/.tmux/.tmux.conf
    dest: ~/.config/tmux/tmux.conf
    state: link

- name: Clone powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k

- name: Ensure Hammerspoon directory exists
  file:
    path: ~/.hammerspoon
    state: directory

- name: Symlink Hammerspoon files
  file:
    src: "{{ role_path }}/files/hammerspoon/{{ item }}.lua"
    dest: "~/.hammerspoon/{{ item }}.lua"
    state: link
  loop:
    - init
    - hotkeys
    - open
    - screens
